// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8TuquKDSaP7aCzZsRIjZmNf2L6qAY_E',
    appId: '1:596599153604:web:b6fba9ecc44d7af2157a91',
    messagingSenderId: '596599153604',
    projectId: 'comroapps-704b9',
    authDomain: 'comroapps-704b9.firebaseapp.com',
    storageBucket: 'comroapps-704b9.appspot.com',
    measurementId: 'G-498RT0HVG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszWNtiH8YjRRntViDo5IH2x6SvI8Er6w',
    appId: '1:596599153604:android:0a751e05098bbc80157a91',
    messagingSenderId: '596599153604',
    projectId: 'comroapps-704b9',
    storageBucket: 'comroapps-704b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAxLSN2n5Hkm__PDke15W7MvT4zWL1WI',
    appId: '1:596599153604:ios:c4ed0ff0f606f91f157a91',
    messagingSenderId: '596599153604',
    projectId: 'comroapps-704b9',
    storageBucket: 'comroapps-704b9.appspot.com',
    androidClientId: '596599153604-vfcjsuobhdva0a1k9aos3eqe4srh7v58.apps.googleusercontent.com',
    iosClientId: '596599153604-bh7oiv5larcs5gpmnhof6i5pa3qt5kdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.comroAlt',
  );

}